create database testdb
GO

/*
Wieviele Fehler:

--Sortierung
Pfade!  Log und Daten trennen
Anfangsgröße: 8MB (log und Daten).. in 3 Jahren erwartet
Wachstumsraten: 64MB (früher: 1 MB Daten und 10% Logfile)

--Logfiles haben VLFs

----100MB-----------------------------
xxx!xxx!xxx!xxxx!xxx!xxx!xxx!xxx!xxx
-------------------------------------

--Logfiles sollten nicht mehr als ca 50 VLFs

--je größer das Wachstum der Logifles desto größer auch die VLFs intern
--kann man messen-- Siehe Script


*/

CREATE DATABASE [testdb2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'testdb2', FILENAME = N'C:\_SQLDBS\testdb2.mdf' , SIZE = 1024KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'testdb2_log', FILENAME = N'C:\_SQLDBS\testdb2_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [testdb2] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [testdb2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [testdb2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [testdb2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [testdb2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [testdb2] SET ARITHABORT OFF 
GO
ALTER DATABASE [testdb2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [testdb2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [testdb2] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [testdb2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [testdb2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [testdb2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [testdb2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [testdb2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [testdb2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [testdb2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [testdb2] SET  DISABLE_BROKER 
GO
ALTER DATABASE [testdb2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [testdb2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [testdb2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [testdb2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [testdb2] SET  READ_WRITE 
GO
ALTER DATABASE [testdb2] SET RECOVERY FULL 
GO
ALTER DATABASE [testdb2] SET  MULTI_USER 
GO
ALTER DATABASE [testdb2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [testdb2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [testdb2] SET DELAYED_DURABILITY = DISABLED 
GO
USE [testdb2]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [testdb2]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [testdb2] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
